name: build.node.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.6.1]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: export NODE_OPTIONS=--openssl-legacy-provider && npm run build --if-present

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-artifact
        path: ./build